<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_hightop-forms</name>
   <tag></tag>
   <elementGuidId>9cd00789-163b-4a71-9ee6-f95c4590d949</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;csstransforms csstransforms3d csstransitions js flexbox flexboxlegacy canvas canvastext postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache&quot;]/body[@class=&quot;page-header-fixed bg-1&quot;]/div[@class=&quot;modal-shiftfix&quot;]/div[@class=&quot;navbar navbar-fixed-top scroll-hide&quot;]/div[@class=&quot;container-fluid main-nav clearfix&quot;]/div[@class=&quot;nav-collapse&quot;]/ul[@class=&quot;nav&quot;]/li[@class=&quot;dropdown&quot;]/a[1]/span[@class=&quot;hightop-forms&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hightop-forms</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Se7en - Bootstrap 3 Responsive/iframe_preview-frame</value>
   </webElementProperties>
</WebElementEntity>
